project_id = "bfmofulvsqojwuqyhfqq"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.distribute-daily-rewards]
verify_jwt = false

[functions.distribute-weekly-rewards]
verify_jwt = false

[functions.distribute-monthly-rewards]
verify_jwt = false

[edge-runtime]
enabled = true